name: Build (develop)

on:
  push:
    branches:
      - develop

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: windows-defender
        run: powershell -Command Add-MpPreference -ExclusionPath "."
      - name: heap-size
        run: powershell $env:NODE_OPTIONS="--max-old-space-size=4096"
      - name: install
        run: yarn install --network-timeout 1000000
      - name: build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn xy build -v
      - name: cycle
        run: yarn cycle
      - name: build-storybook
        run: yarn build-storybook
